version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerfileFrontendRECUC
    container_name: frontendRECUC
    ports:
      - '5173:5173'
    networks:
      - redwebRECUC

  backend:
    build:
      context: ./backend
      dockerfile: DockerfileBackendRECUC
    container_name: backendRECUC
    ports:
      - '8000:8000'
    env_file:
      - .env
    networks:
      - redwebRECUC

  database:
    image: mysql:8.0
    container_name: databaseRECUC
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - redwebRECUC

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminRECUC
    environment:
      PMA_HOST: database
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    networks:
      - redwebRECUC

  web:
    build:
      context: ./web
      dockerfile: DockerfileWebRECUC
    container_name: webRECUC
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./web/certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
      - phpmyadmin
    networks:
      - redwebRECUC

networks:
  redwebRECUC:
    driver: bridge
